/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-06-01 08:22:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.payment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("img {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("div.final_price {\r\n");
      out.write("    height: 69px;\r\n");
      out.write("    border-top: 1px solid #cbcfdb;\r\n");
      out.write("    border-bottom: 1px solid #cbcfdb;\r\n");
      out.write("    color: red;\r\n");
      out.write("    font: bold 30px Tahoma, sans-serif;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 230%;\r\n");
      out.write("}\r\n");
      out.write("#button1 {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>결제확인창</h2>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"etc_payment\">\r\n");
      out.write("\t\t\t<span style=\"display:\"> <span style=\"display: none\"><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"pmCard\" name=\"pay\" checked=\"checked\">신용카드</span>\r\n");
      out.write("\t\t\t\t<label class=\"selected\"><input type=\"radio\" id=\"cardType0\"\r\n");
      out.write("\t\t\t\t\tname=\"pay\" checked=\"checked\">신용카드(일반)</label> <label><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"cardType1\" name=\"pay\">신용카드(법인)</label> <label><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"cardType2\" name=\"pay\">해외발급카드</label>\r\n");
      out.write("\t\t\t</span> <span style=\"display: none\" disabled=\"\"> <label><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"pmRealtime\" name=\"pay\">실시간계좌이체</label>\r\n");
      out.write("\t\t\t</span> <span style=\"display:\"> <label><input type=\"radio\"\r\n");
      out.write("\t\t\t\t\tid=\"pmAccount\" name=\"pay\">무통장입금</label>\r\n");
      out.write("\t\t\t</span> <span style=\"display: none\" disabled=\"\"> <label><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"pmPhone\" name=\"pay\">휴대폰결제</label>\r\n");
      out.write("\t\t\t</span> <span style=\"display: none\" disabled=\"\"> <label><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"pmPayco\" name=\"pay\">PAYCO</label>\r\n");
      out.write("\t\t\t</span> <span style=\"display: none\" disabled=\"\"> <label><input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" id=\"pmTcash\" name=\"pay\">모바일티머니</label>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table border=\"1px solid black\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">카드선택</th>\r\n");
      out.write("\t\t\t\t\t<td bordercolor=\"red\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"target\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"resources/image/dnfl.png\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"resources/image/shdguq.png\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"resources/image/toakdmf.png\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"resources/image/rnrals.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>카드선택</th>\r\n");
      out.write("\t\t\t\t\t<td><select style=\"width: 140px;\"><option value=\"\">선택하세요</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>제주카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>신협체크카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>광주카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>수협카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>전북카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>우체국카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>KDB카드</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>KB[구 현대]증권체크카드</option></select></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label>할부방식</label></th>\r\n");
      out.write("\t\t\t\t\t<td><select>\r\n");
      out.write("\t\t\t\t\t\t\t<option>일시불</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>1개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>3개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>4개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>5개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>6개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>7개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>8개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>9개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>10개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>11개월</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>12개월</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>결제안내</th>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"#\"><span>간편결제안내</span></a> <a href=\"#\"><span>공인인증안내</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span>안전결제안내</span></a> <a href=\"#\"><span>안심클릭안내</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span>해외발급카드안내</span></a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<h4><span id=\"finalPayTxt \">신용카드</span> 최종 결제금액</h4>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"final_price container\" id=\"CalcAmount\">8,000<span>원</span></div>\r\n");
      out.write("\t<div class=\"my_agrmt_wrap container\">\r\n");
      out.write("\t\t\t<h5><input type=\"checkbox\" id=\"idArmt\" name=\"idArmt\"> 개인정보 판매자 제공에 동의합니다.</h5>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"id_agrmt\">\r\n");
      out.write("\t\t\t\t\t<p>고객님께서는 아래 내용에 대하여 동의를 거부하실 수 있으며, 거부시 상품 배송, CS가 제한됩니다.</p>\r\n");
      out.write("\t\t\t\t\t<table border=\"1px solid black\">\r\n");
      out.write("\t\t\t\t\t\t<p>개인정보 수집 내용</p>\r\n");
      out.write("\t\t\t\t\t\t<colgroup><col width=\"30%\"><col width=\"70%\"></colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>제공받는자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>[예스이십사 주식회사]</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>목적</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>주문상품의 배송(예약), 고객상담 및 불만처리</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>항목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>성명, 주소, 연락처(안심번호 적용 시 연락처는 제외), 개인통관고유부호(선택시), 공동현관 출입번호(입력시)</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>보유기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>구매확정 후 3개월까지</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t<h5><input type=\"checkbox\"> 개인정보 수집 및 이용에 동의합니다.</h5>\r\n");
      out.write("\t\t<p>고객님께서는 아래 내용에 대하여 동의를 거부하실 수 있으며, 거부 시 상품배송, 구매 및 결제, 일부 포인트 적립이 제한됩니다.</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h5><input type=\"checkbox\">주문 상품정보에 동의합니다.</h5>\r\n");
      out.write("\t\t<p>주문 상품의 상품명,가격,배송정보에 동의합니다</p>\r\n");
      out.write("\t\t<input type=\"checkbox\">위 내용을 모두 확인하였으며, 이 내용에 모두 동의하시겠습니까?<br>\r\n");
      out.write("\t\t <button type=\"button\" class=\"btn btn-success\" id=\"button1\" onclick=\"location='semi.Project?page=payment&code=3'\">결제하기</button>\r\n");
      out.write("  <button type=\"button\" class=\"btn btn-danger\" id=\"button1\">취소하기</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
