/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-06-01 06:29:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.commercial;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/commercial/../commercial/footer.jsp", Long.valueOf(1590978578514L));
    _jspx_dependants.put("/WEB-INF/views/commercial/../commercial/sidemenu.jsp", Long.valueOf(1590938426892L));
    _jspx_dependants.put("/WEB-INF/views/commercial/../commercial/header_index.jsp", Long.valueOf(1590992933089L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Grayscale - Start Bootstrap Theme</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Font Awesome icons (free version)-->\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Varela+Round\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"resources/css/commercial/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light fixed-top\"\r\n");
      out.write("\t\tid=\"mainNav2\">\r\n");
      out.write("\t\t<div class=\"container .col-md-12\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand js-scroll-trigger\" href=\"hyundoo.Project?page=commercial&code=1\">상권 분석</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\tMenu<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item2\"><a class=\"nav-link2 js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">강온유님 환영합니다.</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=index\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=commercial&code=98\">매물</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=commercial&code=97\">매물등록</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">내정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#projects\">로그아웃</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"contact-section bg-white\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div id=\"map\" class=\"col-lg-12\" style=\"width: 100%; height: 820px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wejnreaybi\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar seoul = new naver.maps.LatLngBounds(new naver.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t37.42829747263545, 126.76620435615891),\r\n");
      out.write("\t\t\t\t\tnew naver.maps.LatLng(37.7010174173061, 127.18379493229875));\r\n");
      out.write("\t\t\tvar map = new naver.maps.Map(document.getElementById('map'), {\r\n");
      out.write("\t\t\t\tminZoom : 11.5,\r\n");
      out.write("\t\t\t\tzoom : 11.5,\r\n");
      out.write("\t\t\t\tmapTypeId : 'normal',\r\n");
      out.write("\t\t\t\tcenter : new naver.maps.LatLng(37.4098871, 126.989261),\r\n");
      out.write("\t\t\t\tmaxBounds : seoul,\r\n");
      out.write("\t\t\t\tlogoControl : false,\r\n");
      out.write("\t\t\t\tbaseTileOpacity : 1\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t/* var HOME_PATH = window.HOME_PATH || '.'; */\r\n");
      out.write("\t\t\tnaver.maps.Event.once(map, 'init_stylemap', function() {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : 'resources/js/commercial/seoul_municipalities_geo.json',\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : startDataLayer\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//geoJson 레이어 추가하기\r\n");
      out.write("\t\t\tfunction startDataLayer(geojson) {\r\n");
      out.write("\t\t\t\tmap.data.addGeoJson(geojson);\r\n");
      out.write("\t\t\t\tmap.data.setStyle(function(feature) {\r\n");
      out.write("\t\t\t\t\tvar color = 'black';\r\n");
      out.write("\t\t\t\t\tif (feature.getProperty('isColorful')) {\r\n");
      out.write("\t\t\t\t\t\tcolor = feature.getProperty('color');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn {\r\n");
      out.write("\t\t\t\t\t\tfillColor : 'white',\r\n");
      out.write("\t\t\t\t\t\tstrokeColor : color,\r\n");
      out.write("\t\t\t\t\t\tstrokeWeight : 2,\r\n");
      out.write("\t\t\t\t\t\ticon : null\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('click', function(e) {\r\n");
      out.write("\t\t\t\t\te.feature.setProperty('isColorful', true);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('dblclick', function(e) {\r\n");
      out.write("\t\t\t\t\tvar bounds = e.feature.getBounds();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (bounds) {\r\n");
      out.write("\t\t\t\t\t\tmap.panToBounds(bounds);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('mouseover', function(e) {\r\n");
      out.write("\t\t\t\t\tmap.data.overrideStyle(e.feature, {\r\n");
      out.write("\t\t\t\t\t\tstrokeWeight : 8,\r\n");
      out.write("\t\t\t\t\t\ticon : 'resources/js/commercial/seoul_municipalities_geo.json'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('mouseout', function(e) {\r\n");
      out.write("\t\t\t\t\tmap.data.revertStyle();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/* \tfor (var i = 0; i < ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${array.length}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; i++) {\r\n");
      out.write("\t\t\t\t\tvar marker = new naver.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\tposition: new naver.maps.LatLng(x,y),\r\n");
      out.write("\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\ttitle : '항목'\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}*/\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<link href=\"resources/css/commercial/sidebar.css?after\" rel=\"stylesheet\" />\r\n");
      out.write("<div id=\"rightSide\">\r\n");
      out.write("\t<div id=\"right_zzim\">\r\n");
      out.write("\t\t<div class=\"recTit\">\r\n");
      out.write("\t\t\t최근본상품 <span id=recentCnt></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul></ul>\r\n");
      out.write("\t\t<!-- 본 상품이 뿌려질 부분  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer bg-black small text-center text-white-50\"><div class=\"container\">Copyright ⓒ   Your Website 2020</div></footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <!-- <script>\r\n");
      out.write("\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=1'\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#combobox1').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$('#combobox1').change(function(){\r\n");
      out.write("\t\t\t\t\t\t\t//마커 추가하기.\r\n");
      out.write("\t\t\t\t\t\t\t\tvar param = $(this).val();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=5&target='+encodeURIComponent(param);\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(typeof(d));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar myObj = JSON.parse(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar i = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//console.log(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor ( var e in myObj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//console.log(\"e : \"+e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar marker= new naver.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    position: new naver.maps.LatLng(myObj[e].lat, myObj[e].lng),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    map: map\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=2'\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#combobox2').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t\t$('#combobox2')\r\n");
      out.write("\t\t\t\t\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar param = $('#combobox2').val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=3&largeName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('#combobox3')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(\"Error : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t\t$('#combobox3')\r\n");
      out.write("\t\t\t\t\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar largeName = $('#combobox2')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar mediumName = $('#combobox3')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=4&largeName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(largeName)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"&mediumName=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(mediumName)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('#combobox4')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(\"Error : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tfunction goPopup(){\r\n");
      out.write("\t\t\t\t\t\t// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("\t\t\t\t\t\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\t\t\t\t\tvar pop = window.open(\"semi.Project?page=commercial&subcode=96\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\t\t\t\t    //var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t\t\t\t\t}function jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn,detBdNmList,bdNm,bdKdcd,siNm,sggNm,emdNm,liNm,rn,udrtYn,buldMnnm,buldSlno,mtYn,lnbrMnnm,lnbrSlno,emdNo){\r\n");
      out.write("\t\t\t\t\t\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("\t\t\t\t\t\t//document.form.roadFullAddr.value = roadFullAddr;\r\n");
      out.write("\t\t\t\t\t\t$('#roadAddrPart1').val(roadAddrPart1);\r\n");
      out.write("\t\t\t\t\t\t$(\"#addrDetail\").val(addrDetail);\r\n");
      out.write("\t\t\t\t\t\t$(\"#zipNo\").val(zipNo);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</script> -->\r\n");
      out.write("\t\t\t\t<script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("\t\t\t\t<!-- \"검색\" 단추를 누르면 팝업 레이어가 열리도록 설정한다 -->\r\n");
      out.write("\t\t\t\t<script> $(function() { $(\"#postcodify_search_button\").postcodifyPopUp(); }); </script>\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Third party plugin JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
