/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-06-01 08:34:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.estate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class estateDetile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/estate/../include/header_menu.jsp", Long.valueOf(1590996486274L));
    _jspx_dependants.put("/WEB-INF/views/estate/../estate/side.jsp", Long.valueOf(1590971028025L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1588293609789L));
    _jspx_dependants.put("/WEB-INF/views/estate/../include/footer.jsp", Long.valueOf(1590935123427L));
    _jspx_dependants.put("jar:file:/C:/ikosmo64/webapp/projectworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/uiProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/estate/../include/header_index.jsp", Long.valueOf(1590932179513L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"EUC-KR\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Grayscale - Start Bootstrap Theme</title>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Varela+Round\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"resources/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\t  <link href=\"resources/css/estate_one/estate_on.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t    <link href=\"resources/css/estate_one/th_bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t      <link href=\"resources/css/estate_one/th_styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t         <link href=\"resources/css/estate_one/sideber.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("       \r\n");
      out.write("          <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\" id=\"mainNav2\" >\r\n");
      out.write("         <div class=\"container .col-md-12\">\r\n");
      out.write("                <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">메인메뉴테스트</a><button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Menu<i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                 <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                        <li class=\"nav-item2\"><a class=\"nav-link2 js-scroll-trigger\" href=\"#about\">강온유님 환영합니다.</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"semi.Project?page=estate&code=2\">매물 등록</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" onclick=\"location = 'semi.Project?page=community&code=1'\">커뮤니티</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#signup\">고객센터</a></li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"semi.Project?page=commercial&subcode=98\">상가</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                      <ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#about\">내정보</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#projects\">로그아웃</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            </nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"contact-section container topma \">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"th_card bg-white property_border_st\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h3 class=\"th_card-header  property_color bg-white\">오피스텔 ·\r\n");
      out.write("\t\t\t미사역마이움푸르지오시티</h3>\r\n");
      out.write("\t\t<div class=\"th_card-body bg-white\">\r\n");
      out.write("\t\t\t<h3 class=\"th_card-title \">월세 500/40 만원</h3>\r\n");
      out.write("\t\t\t<h6 class=\"th_card-subtitle th_text-muted \">풀옵션 , 관리비 : 5만원</h6>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<img class=\"th_property_img\" src=\"assets/img/home.jpg\"\r\n");
      out.write("\t\t\talt=\"Card image\" >\r\n");
      out.write("\t\t\t<img class=\"th_property_subimg\" src=\"assets/img/home2.jpg\"\r\n");
      out.write("\t\t\talt=\"Card image\">\r\n");
      out.write("\t\t\t<img class=\"th_property_subimg\" src=\"assets/img/home3.jpg\"\r\n");
      out.write("\t\t\talt=\"Card image\" >\r\n");
      out.write("\t\t\t<img class=\"th_property_subimg\" src=\"assets/img/home4.jpg\"\r\n");
      out.write("\t\t\talt=\"Card image\" >\r\n");
      out.write("\t\t\t<img class=\"th_property_subimg\" src=\"assets/img/home.jpg\"\r\n");
      out.write("\t\t\talt=\"Card image\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"topma bg-white\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs \">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"tab\" href=\"#home\">매물 정보 </a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"tab\"\r\n");
      out.write("\t\t\t\t\thref=\"#profile\">상세 설명</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link \" data-toggle=\"tab\"\r\n");
      out.write("\t\t\t\t\thref=\"#\">그 외 만들고 싶은 탭 추가 하기</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"myTabContent\" class=\"tab-content bg-white container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"tab-pane fade active show th_page_space img-circle\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-align: center;\" id=\"home\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table class=\"type11\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>해당층/건물층 : </strong> 10층 / 23층</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>전용/계약면적 : </strong> 120.48 / 49.86㎡</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>난방종류 : </strong> 지역난방</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>빌트인 : </strong> 빌트인 주방</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>준공년월 : </strong> 2020.08준공</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>총 세대수 : </strong> 1090세대</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>세대당 주차수 : </strong> 0.7대</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>반려동물 : </strong> 가능</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>베란다/발코니 : </strong> 없음</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>전세자금대출 : </strong> 가능</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><strong>입주가능일 : </strong> 2020.07.08</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"container topma\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"type12\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"cols\"><h1>주인이 직접 쓴 상세 설명 데이터 제목 !</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<pre>에덴부동산.연중무휴24시간상담가능.상대농대전철우부근.용봉동.저희도기다리느라지쳤던방.단독중개입니다.신속하고빠르게중개해드립니다.</pre>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><h3>주인이 직접 쓴 상세 설명 데이터 내용 !</h3> <pre>\r\n");
      out.write("예시 ) :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("편의 시설 도보 5분 \r\n");
      out.write("\r\n");
      out.write("리뷰 만족도 1등\r\n");
      out.write("\r\n");
      out.write("보증금 분납 OK\r\n");
      out.write("\r\n");
      out.write("여성분들도 안심하실 수 있는 방\r\n");
      out.write("\r\n");
      out.write(" 인근 편의시설이 있어 편리합니다\r\n");
      out.write("\r\n");
      out.write("허위매물 보단 실매물로 승부보겠습니다\r\n");
      out.write("\r\n");
      out.write("다른 구조의 원룸 및 투룸도 가격대별\r\n");
      out.write("  다양하게 있으니 일단 연락주세요\r\n");
      out.write("\r\n");
      out.write("보증금 및 월세 조절 최대한 맞춰드립니다\r\n");
      out.write("\r\n");
      out.write("전화가 부끄러우신분은 카톡상담 youhyun1099\r\n");
      out.write("\r\n");
      out.write("저도 어린시절부터 자취를 해왔습니다 제가 살기 싫은 방은 중개하지 않습니다\r\n");
      out.write("\r\n");
      out.write("상가 월세 원룸 건물 매입 문의도 받아요  </pre></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade th_page_space container\" id=\"profile\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"p_list\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"th_a\" href=\"#a\">가격 정보 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"th_a\" href=\"#b\">옵션 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"th_a\" href=\"#c\">위치 및 주변시설</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"th_a\" href=\"#d\">다방면 스코어</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"th_a\" href=\"#e\">이 공인중개사 다른방 </a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"a\" class=\"th_b\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"container\" >가격 정보를 확인 할수 있는\r\n");
      out.write("\t\t\t\t\t\t\t부분 입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testestest\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"b\" class=\"th_b\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"container\" >옵션 정보를 확인 할수 있는\r\n");
      out.write("\t\t\t\t\t\t\t부분 입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testestest\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"c\" class=\"th_b\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"container\" >위치 및 주변시설 정보를 확인\r\n");
      out.write("\t\t\t\t\t\t\t할수 있는 부분 입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testestest\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"d\" class=\"th_b\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"container\" >다방면 스코어 정보를 확인 할수\r\n");
      out.write("\t\t\t\t\t\t\t있는 부분 입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testestest\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"e\" class=\"th_b\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"container\" >이 공인중개사 다른방 정보를\r\n");
      out.write("\t\t\t\t\t\t\t확인 할수 있는 부분 입니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testestest\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade th_page_space\" id=\"quote\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade th_page_space\" id=\"dropdown2\">\r\n");
      out.write("\t\t\t\t\t<p>Trust fund seitan letterpress, keytar raw denim keffiyeh\r\n");
      out.write("\t\t\t\t\t\tetsy art party before they sold out master cleanse gluten-free\r\n");
      out.write("\t\t\t\t\t\tsquid scenester freegan cosby sweater. Fanny pack portland seitan\r\n");
      out.write("\t\t\t\t\t\tDIY, art party locavore wolf cliche high life echo park Austin.\r\n");
      out.write("\t\t\t\t\t\tCred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out\r\n");
      out.write("\t\t\t\t\t\tfarm-to-table VHS viral locavore cosby sweater.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"th_card bg-white property_border_st\">\r\n");
      out.write("\t\t<div class=\"th_card-body\">\r\n");
      out.write("\t\t\t<h3 class=\"th_card-title\">미사역미래공인중개사사무소</h3>\r\n");
      out.write("\t\t\t<h4 class=\"th_card-subtitle mb-2 text-muted\">이은희</h4>\r\n");
      out.write("\t\t\t<p class=\"th_card-text\">언제든지 편하게 연락주세요 .</p>\r\n");
      out.write("\t\t\t<p class=\"th_card-text\">tel - 010-5555-6666 , 02) 222 - 5656</p>\r\n");
      out.write("\t\t\t<a href=\"tel:010-7503-6251\" class=\"th_card-link\">전화 걸기</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"th_card-link\">지도 표시 하기</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/sideber.css?after\" rel=\"stylesheet\" />\r\n");
      out.write("<div id=\"rightSide\">\r\n");
      out.write("\t<div id=\"right_zzim\">\r\n");
      out.write("\t\t<div class=\"recTit\">\r\n");
      out.write("\t\t\t최근본상품 <span id=recentCnt></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul></ul>\r\n");
      out.write("\t\t<!-- 본 상품이 뿌려질 부분  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer bg-black small text-center text-white-50\"><div class=\"container\">Copyright ⓒ   Your Website 2020</div></footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("      \r\n");
      out.write("        <script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Third party plugin JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"resources/js/scripts.js\"></script>\r\n");
      out.write("        <script src=\"resources/js/text.js\"></script>\r\n");
      out.write("         <script>\r\n");
      out.write("         $(function() {\r\n");
      out.write("        \t \r\n");
      out.write("        \t    $(\".typer\").typed({\r\n");
      out.write("         \t\t    strings: [\" C조 Project\", \" Test용 문구\", \" 조장 : 박현두\", \" 대박임\"],\r\n");
      out.write("         \t\t    typeSpeed: 500,\r\n");
      out.write("         \t\t    backDelay: 1500,\r\n");
      out.write("         \t\t    showCursor: false\r\n");
      out.write("         \t\t});\r\n");
      out.write("        \t    $('#filter_close').click(function() {\n");
      out.write("        \t    \t$('.filter-page').slideUp(1000).addClass('invisible').removeClass('visible');\r\n");
      out.write("        \t    \tclassName='invisible';\r\n");
      out.write("        \t    \tinvisible='invisible';\r\n");
      out.write("        \t    \tvisible='visible';\r\n");
      out.write("        \t    \t        \n");
      out.write("        \t    })\r\n");
      out.write("        \t    \r\n");
      out.write("        \t    $('.card').click(function() {\n");
      out.write("        \t    \t\tvar num=$(this).index();\r\n");
      out.write("        \t    \t\tconsole.log(num)\n");
      out.write("        \t    });\r\n");
      out.write("        \t    var invisible='invisible';\r\n");
      out.write("        \t    var visible='visible';\r\n");
      out.write("        \t    var className='invisible';\r\n");
      out.write("        \t   $('.filter-div').children('.btn').click(function() {\r\n");
      out.write("        \t\t  \r\n");
      out.write("           \t\t \r\n");
      out.write("        \t\t   \t$('.filter-page').removeClass(invisible);\r\n");
      out.write("       \t   \t\t\t$('.filter-page').addClass(visible);\r\n");
      out.write("        \t\t \tif(className === 'visible'){\r\n");
      out.write("        \t\t \t      \r\n");
      out.write("        \t\t \t\t$('.filter-page').slideUp(1000);\r\n");
      out.write("        \t\t \t\t\r\n");
      out.write("        \t\t \t}else {\r\n");
      out.write("        \t\t \t\t\r\n");
      out.write("        \t\t \t\t$('.filter-page').slideDown(1000);\r\n");
      out.write("        \t\t \t\t\r\n");
      out.write("        \t\t \t}\n");
      out.write("        \t\t \t\t\r\n");
      out.write("            \t   \t\tclassName=visible;\r\n");
      out.write("            \t   \t\tvisible=invisible;\r\n");
      out.write("            \t   \t\tinvisible=className;\n");
      out.write("        \t\t \t\r\n");
      out.write("        \t\t \t\n");
      out.write("        \t\t \t\n");
      out.write("        \t   });\r\n");
      out.write("        \t    \r\n");
      out.write("        \t    \r\n");
      out.write("\t\t});\r\n");
      out.write("         \r\n");
      out.write("     \r\n");
      out.write("                    </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
