/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-06-01 08:29:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.commercial;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class commercialMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/ikosmo64/webapp/projectworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/commercial/header_index.jsp", Long.valueOf(1590470146000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1588293610000L));
    _jspx_dependants.put("/WEB-INF/commercial/modal.jsp", Long.valueOf(1590680554000L));
    _jspx_dependants.put("/WEB-INF/commercial/sidemenu.jsp", Long.valueOf(1590537274000L));
    _jspx_dependants.put("/WEB-INF/commercial/footer.jsp", Long.valueOf(1590903350000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Grayscale - Start Bootstrap Theme</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Font Awesome icons (free version)-->\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Varela+Round\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light fixed-top\"\r\n");
      out.write("\t\tid=\"mainNav2\">\r\n");
      out.write("\t\t<div class=\"container .col-md-12\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand js-scroll-trigger\" href=\"hyundoo.Project?page=commercial&subcode=0\">상권 분석</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\tMenu<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item2\"><a class=\"nav-link2 js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">강온유님 환영합니다.</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=index&subcode=0\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=commercial&subcode=98\">매물</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=commercial&subcode=97\">매물등록</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">내정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#projects\">로그아웃</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link href=\"css/sidebar.css?after\" rel=\"stylesheet\" />\r\n");
      out.write("<div id=\"rightSide\">\r\n");
      out.write("\t<div id=\"right_zzim\">\r\n");
      out.write("\t\t<div class=\"recTit\">\r\n");
      out.write("\t\t\t최근본상품 <span id=recentCnt></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul></ul>\r\n");
      out.write("\t\t<!-- 본 상품이 뿌려질 부분  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Content -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<!-- Call to Action Well -->\r\n");
      out.write("\t<script src=\"js/json2.js\"></script>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tclass=\"card text-white bg-secondary my-5 py-4 text-center col-lg-12\">\r\n");
      out.write("\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t<form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t<select id=\"combobox1\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-right: 30px; width: 120px\">\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"text\" autocomplete=\"off\" placeholder=\"Select a State\" class=\"combobox input-large form-control\"> -->\r\n");
      out.write("\t\t\t\t\t<option>구 선택</option>\r\n");
      out.write("\t\t\t\t</select> <select id=\"combobox2\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-right: 30px; width: 120px\">\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"text\" autocomplete=\"off\" placeholder=\"Select a State\" class=\"combobox input-large form-control\"> -->\r\n");
      out.write("\t\t\t\t\t<option>동 선택</option>\r\n");
      out.write("\t\t\t\t</select> <select id=\"combobox3\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-right: 30px; width: 200px\">\r\n");
      out.write("\t\t\t\t\t<option>업종대분류</option>\r\n");
      out.write("\t\t\t\t</select> <select id=\"combobox4\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-right: 30px; width: 250px\">\r\n");
      out.write("\t\t\t\t\t<option>업종중분류</option>\r\n");
      out.write("\t\t\t\t</select> <select id=\"combobox5\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-right: 30px; width: 200px\">\r\n");
      out.write("\t\t\t\t\t<option>업종소분류</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!-- <p class=\"text-white m-0\">지도 위치 선택 버튼 들어올 자리</p> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Heading Row -->\r\n");
      out.write("\t<div class=\"row align-items-center my-5\">\r\n");
      out.write("\t\t<div id=\"map\" class=\"col-lg-7\" style=\"width: 100%; height: 655px;\">\r\n");
      out.write("\t\t\t<!-- <img class=\"img-fluid rounded mb-4 mb-lg-0\" src=\"http://placehold.it/900x400\"> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=wejnreaybi\"></script>\r\n");
      out.write("\t\t<script type=\"js/MarkerClustering.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar seoul = new naver.maps.LatLngBounds(new naver.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t37.42829747263545, 126.76620435615891),\r\n");
      out.write("\t\t\t\t\tnew naver.maps.LatLng(37.7010174173061, 127.18379493229875));\r\n");
      out.write("\t\t\tvar map = new naver.maps.Map(document.getElementById('map'), {\r\n");
      out.write("\t\t\t\tminZoom : 10.5,\r\n");
      out.write("\t\t\t\tzoom : 10.5,\r\n");
      out.write("\t\t\t\tmapTypeId : 'normal',\r\n");
      out.write("\t\t\t\tcenter : new naver.maps.LatLng(37.4098871, 126.989261),\r\n");
      out.write("\t\t\t\tmaxBounds : seoul,\r\n");
      out.write("\t\t\t\tbaseTileOpacity : 1,\r\n");
      out.write("\t\t\t\tscaleControl : false,\r\n");
      out.write("\t\t\t\tlogoControl : false,\r\n");
      out.write("\t\t\t\tmapDataControl : false,\r\n");
      out.write("\t\t\t\tzoomControl : false,\r\n");
      out.write("\t\t\t\tmapTypeControl : false\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tnaver.maps.Event.once(map, 'init_stylemap', function() {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : 'json/gangnam.json',\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : startDataLayer\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//geoJson 레이어 추가하기\r\n");
      out.write("\t\t\tfunction startDataLayer(geojson) {\r\n");
      out.write("\t\t\t\tmap.data.addGeoJson(geojson);\r\n");
      out.write("\t\t\t\tmap.data.setStyle(function(feature) {\r\n");
      out.write("\t\t\t\t\tvar color = 'black';\r\n");
      out.write("\t\t\t\t\tif (feature.getProperty('isColorful')) {\r\n");
      out.write("\t\t\t\t\t\tcolor = feature.getProperty('color');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn {\r\n");
      out.write("\t\t\t\t\t\tfillColor : 'white',\r\n");
      out.write("\t\t\t\t\t\tstrokeColor : color,\r\n");
      out.write("\t\t\t\t\t\tstrokeWeight : 2,\r\n");
      out.write("\t\t\t\t\t\ticon : null\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('click', function(e) {\r\n");
      out.write("\t\t\t\t\te.feature.setProperty('isColorful', true);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('dblclick', function(e) {\r\n");
      out.write("\t\t\t\t\tvar bounds = e.feature.getBounds();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (bounds) {\r\n");
      out.write("\t\t\t\t\t\tmap.panToBounds(bounds);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('mouseover', function(e) {\r\n");
      out.write("\t\t\t\t\tmap.data.overrideStyle(e.feature, {\r\n");
      out.write("\t\t\t\t\t\tstrokeWeight : 8,\r\n");
      out.write("\t\t\t\t\t\ticon : 'json/gangnam.json'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tmap.data.addListener('mouseout', function(e) {\r\n");
      out.write("\t\t\t\t\tmap.data.revertStyle();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div class=\"col-lg-5\" id=\"information\">\r\n");
      out.write("\t\t\t<h1 class=\"font-weight-light\">입지 선정 서비스</h1>\r\n");
      out.write("\t\t\t<p>창업을 원하시는 입지의 좌표를 선택해주세요. 그 입지 근처의 유동인구, 주변 상권분석, 실거래가 등 다양한\r\n");
      out.write("\t\t\t\t정보를 제공해드립니다. 조금 더 자세한 정보를 얻고 싶으시면 상게하게 검색해보세요.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- <script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('#combobox1').change(function() {\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script> -->\r\n");
      out.write("\t\t<!-- /.col-md-4 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.row -->\r\n");
      out.write("\t<!-- Content Row -->\r\n");
      out.write("\t<div class=\"row\" id=\"product\">\r\n");
      out.write("\t\t<div class=\"col-md-4 mb-5\">\r\n");
      out.write("\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"card-title\">매물 1</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">매물 정보 이미지 등 들어올 자리</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t\t<button onclick=\"open_pop()\" class=\"btn btn-primary btn-sm\">More\r\n");
      out.write("\t\t\t\t\t\tInfo</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-md-4 -->\r\n");
      out.write("\t\t<div class=\"col-md-4 mb-5\">\r\n");
      out.write("\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"card-title\">매물 2</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">매물 정보 이미지 등 들어올 자리</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t\t<button onclick=\"open_pop()\" class=\"btn btn-primary btn-sm\">More\r\n");
      out.write("\t\t\t\t\t\tInfo</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-md-4 -->\r\n");
      out.write("\t\t<div class=\"col-md-4 mb-5\">\r\n");
      out.write("\t\t\t<div class=\"card h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"card-title\">매물 3</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">매물 정보 이미지 등 들어올 자리</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t\t<button onclick=\"open_pop()\" class=\"btn btn-primary btn-sm\">More\r\n");
      out.write("\t\t\t\t\t\tInfo</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-md-4 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.row -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/modal.css?after\" rel=\"stylesheet\" />\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("\t<!-- Modal content -->\r\n");
      out.write("\t<div class=\"modal-content\">\r\n");
      out.write("\t\t<h3>상가/점포 매물등록 신청</h3>\r\n");
      out.write("\t\t<div class=\"row\" id=\"regist\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6 mb-4 mb-md-0\">\r\n");
      out.write("\t\t\t\t<!-- <div class=\"card-body text-center\"> -->\r\n");
      out.write("\t\t\t\t물건 정보\r\n");
      out.write("\t\t\t\t<div class=\"card py-6 h-100\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%; border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 500px; height: 200px;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>소재지\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" id='zipNo' name=\"zipNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 10px\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"postcodify_search_button\" onclick=\"goPopup();\">검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br /> <input type=\"text\" id=\"roadAddrPart1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"roadAddrPart1\" disabled style=\"width: 300px\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" id=\"addrDetail\" name=\"addrDetail\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>물건 구분\r\n");
      out.write("\t\t\t\t\t\t\t<td><select id=\"law\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"근린상가\">근린상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"단지내상가\">단지내상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"복합상가\">복합상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"일반상가\">일반상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"기타상가\">기타상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>매물 종류</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select id=\"law\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"매매\">매매</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"전세\">전세</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"월세\">월세</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t상호상가\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>해당 층</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t면적\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"> 평</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>실면적</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"> 평</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t현업종\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>상가입차법</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select id=\"law\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">대상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">비대상</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<!-- <hr class=\"my-4\" /> -->\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"small text-black-50\">현두 담당</div> -->\r\n");
      out.write("\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 mb-4 mb-md-0\">\r\n");
      out.write("\t\t\t\t상권 정보\r\n");
      out.write("\t\t\t\t<div class=\"card py-6 h-100\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 500px; height: 200px;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t특징\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" id='feature'\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"feature\" style=\"width: 370px; height: 40px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t주변 환경\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>추천 업종</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select id=\"law\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 185px; height: 30px; margin-bottom: 10px;\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">현업종과동일</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"서비스업\">서비스업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"학원/교육업\">학원/교육업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"오락업\">오락업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"음식점업\">음식점업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"의류업\">의류업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"자유업\">자유업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"잡화점\">잡화점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"전무점\">전무점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"주류/유흥업\">주류/유흥업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"병원/의료업\">병원/의료업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"기타\">기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <br /> <input type=\"text\" id=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t가격 정보\r\n");
      out.write("\t\t\t\t<span style=\"text-align: right; color: red;\"> 해당부분이 없으면 0을\r\n");
      out.write("\t\t\t\t\t입력하세요.</span>\r\n");
      out.write("\t\t\t\t<div class=\"card py-6 h-100\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 500px; height: 200px;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t매매가\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>전세가</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t보증금\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>월세</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t권리금\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>융자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t담당자 정보\r\n");
      out.write("\t\t\t\t<div class=\"card py-6 h-100\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 500px; height: 200px;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t이름\r\n");
      out.write("\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id='managerName' name=\"managerName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>휴대전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"phoneIdx\" id=\"phoneIdx\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> - <input type=\"tel\" id='managerPhone' name=\"managerPhone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100px\">- <input type=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid='managerPhone' name=\"managerPhone\" style=\"width: 100px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t이메일\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"email\" id=\"email\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>전화</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"\" id=\"\" class=\"stx\" style=\"height: 30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"031\">031</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"032\">032</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"033\">033</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"041\">041</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"042\">042</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"043\">043</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"051\">051</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"052\">052</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"053\">053</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"054\">054</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"055\">055</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"061\">061</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"062\">062</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"063\">063</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"064\">064</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"070\">070</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"050\">050</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> - <input type=\"tel\" id='managerPhone2' name=\"managerPhone2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100px\">- <input type=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid='managerPhone2' name=\"managerPhone2\" style=\"width: 100px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"image-container\">\r\n");
      out.write("\t\t\t<img src=\"img/building1.jpg\"> -\r\n");
      out.write("\t\t\t<img src=\"img/building1.jpg\"> -\r\n");
      out.write("\t\t\t<img src=\"img/building1.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"cursor: pointer; background-color: #DDDDDD; text-align: center; padding-bottom: 10px; padding-top: 10px;\"\r\n");
      out.write("\t\t\tonClick=\"close_pop();\">\r\n");
      out.write("\t\t\t<span class=\"pop_bt\" style=\"font-size: 13pt;\"> 닫기 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction open_pop() {\r\n");
      out.write("\t\t$('#myModal').show();\r\n");
      out.write("\t};\r\n");
      out.write("\t//팝업 Close 기능\r\n");
      out.write("\tfunction close_pop(flag) {\r\n");
      out.write("\t\t$('#myModal').hide();\r\n");
      out.write("\t};\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- Footer-->\r\n");
      out.write("<footer class=\"footer bg-black small text-center text-white-50\">\r\n");
      out.write("\t<div class=\"container\">Copyright ⓒ Your Website 2020</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Bootstrap core JS-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar url = 'hyundoo.Project?page=commercial&subcode=1'\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t$('#combobox1').html(d);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t/* \t$('#combobox1')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t//마커 추가하기.\r\n");
      out.write("\t\t\t\t\t\t\tvar param = $(this).val();\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=6&guname='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param);\r\n");
      out.write("\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(typeof (d));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar myObj = JSON.parse(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar i = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//console.log(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor ( var e in myObj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//console.log(\"e : \"+e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar marker = new naver.maps.Marker(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tposition : new naver.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmyObj[e].lat,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmyObj[e].lng),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmap : map\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}) */\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#combobox1')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar param = $('#combobox1').val()\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=2&guName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#combobox2').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=96&guName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#information').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tvar seoul = new naver.maps.LatLngBounds(new naver.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t37.42829747263545, 126.76620435615891),\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnew naver.maps.LatLng(37.7010174173061, 127.18379493229875));\r\n");
      out.write("\t\t\t\t\t\t\tvar map = new naver.maps.Map(document.getElementById('map'), {\r\n");
      out.write("\t\t\t\t\t\t\t\tminZoom : 10.5,\r\n");
      out.write("\t\t\t\t\t\t\t\tzoom : 10.5,\r\n");
      out.write("\t\t\t\t\t\t\t\tmapTypeId : 'normal',\r\n");
      out.write("\t\t\t\t\t\t\t\tcenter : new naver.maps.LatLng(37.4098871, 126.989261),\r\n");
      out.write("\t\t\t\t\t\t\t\tmaxBounds : seoul,\r\n");
      out.write("\t\t\t\t\t\t\t\tbaseTileOpacity : 0,\r\n");
      out.write("\t\t\t\t\t\t\t\tscaleControl: false,\r\n");
      out.write("\t\t\t\t\t            logoControl: false,\r\n");
      out.write("\t\t\t\t\t            mapDataControl: false,\r\n");
      out.write("\t\t\t\t\t            zoomControl: false,\r\n");
      out.write("\t\t\t\t\t            mapTypeControl: false\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t/* var HOME_PATH = window.HOME_PATH || '.'; */\r\n");
      out.write("\t\t\t\t\t\t\tnaver.maps.Event.once(map, 'init_stylemap', function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : 'json/'+$(this).val()+'.json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : startDataLayer\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar url = 'hyundoo.Project?page=commercial&subcode=3'\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t$('#combobox3').html(d);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#combobox3')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar param = $('#combobox3').val()\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=4&largeName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#combobox4').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#combobox4')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar largeName = $('#combobox3').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar mediumName = $('#combobox4').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=5&largeName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(largeName)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"&mediumName=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(mediumName)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#combobox5').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction goPopup() {\r\n");
      out.write("\t\t// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("\t\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\tvar pop = window.open(\"semi.Project?page=commercial&subcode=96\", \"pop\",\r\n");
      out.write("\t\t\t\t\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\r\n");
      out.write("\t\t// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\t//var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction jusoCallBack(roadFullAddr, roadAddrPart1, addrDetail,\r\n");
      out.write("\t\t\troadAddrPart2, engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn,\r\n");
      out.write("\t\t\tdetBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm, rn, udrtYn,\r\n");
      out.write("\t\t\tbuldMnnm, buldSlno, mtYn, lnbrMnnm, lnbrSlno, emdNo) {\r\n");
      out.write("\t\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("\t\t//document.form.roadFullAddr.value = roadFullAddr;\r\n");
      out.write("\t\t$('#roadAddrPart1').val(roadAddrPart1);\r\n");
      out.write("\t\t$(\"#addrDetail\").val(addrDetail);\r\n");
      out.write("\t\t$(\"#zipNo\").val(zipNo);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("<!-- \"검색\" 단추를 누르면 팝업 레이어가 열리도록 설정한다 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#postcodify_search_button\").postcodifyPopUp();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- Third party plugin JS-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("<!-- Core theme JS-->\r\n");
      out.write("<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
