/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-06-01 08:29:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.commercial;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registeration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/commercial/header_index.jsp", Long.valueOf(1590470146000L));
    _jspx_dependants.put("/WEB-INF/commercial/sidemenu2.jsp", Long.valueOf(1590537218000L));
    _jspx_dependants.put("/WEB-INF/commercial/footer.jsp", Long.valueOf(1590903350000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Grayscale - Start Bootstrap Theme</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("<!-- Font Awesome icons (free version)-->\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Google fonts-->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Varela+Round\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light fixed-top\"\r\n");
      out.write("\t\tid=\"mainNav2\">\r\n");
      out.write("\t\t<div class=\"container .col-md-12\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand js-scroll-trigger\" href=\"hyundoo.Project?page=commercial&subcode=0\">상권 분석</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\tMenu<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item2\"><a class=\"nav-link2 js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">강온유님 환영합니다.</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=index&subcode=0\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=commercial&subcode=98\">매물</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"semi.Project?page=commercial&subcode=97\">매물등록</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#about\">내정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#projects\">로그아웃</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>");
      out.write("\r\n");
      out.write("<section class=\"contact-section bg-white centered\">\r\n");
      out.write("\t<div id=\"container\"\r\n");
      out.write("\t\tstyle=\"width: 1200px; margin: 0 auto; text-align: center;\"\r\n");
      out.write("\t\tclass=\"centered\">\r\n");
      out.write("\t\t<h3>상가/점포 상세정보</h3>\r\n");
      out.write("\t\t<div class=\"col\" id=\"regist\">\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 mb-4 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"card-body text-center\"> -->\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align: left\">물건 정보</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-4 h-100\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%; border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 810px; height: 375px;\"  class=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">소재지</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" id='zipNo' name=\"zipNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 10px\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"postcodify_search_button\" onclick=\"goPopup();\">검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br /> <input type=\"text\" id=\"roadAddrPart1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"roadAddrPart1\" disabled style=\"width: 300px\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"addrDetail\" name=\"addrDetail\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">물건 구분</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select id=\"law\" style=\"width: 200px; height: 30px\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"근린상가\">근린상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"단지내상가\">단지내상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"복합상가\">복합상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"일반상가\">일반상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"기타상가\">기타상가</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">매물 종류</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select id=\"law\" style=\"width: 180px; height: 30px\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"매매\">매매</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"전세\">전세</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"월세\">월세</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">상호상가</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">해당 층</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">면적</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"> 평</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">실면적</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"> 평</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">현업종</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"size\" name=\"size\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">상가입차법</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select id=\"law\" style=\"width: 200px; height: 30px\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">대상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0\">비대상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<!-- <hr class=\"my-4\" /> -->\r\n");
      out.write("\t\t\t\t\t\t<!-- <div class=\"small text-black-50\">현두 담당</div> -->\r\n");
      out.write("\t\t\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align: left\">상권 정보</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-4 h-100\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 810px; height: 200px;\"class=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">특징</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" id='feature'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"feature\" style=\"width: 370px; height: 40px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">주변 환경</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">추천 업종</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><select id=\"law\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 185px; height: 30px; margin-bottom: 10px;\"><option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">현업종과동일</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"서비스업\">서비스업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"학원/교육업\">학원/교육업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"오락업\">오락업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"음식점업\">음식점업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"의류업\">의류업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"자유업\">자유업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"잡화점\">잡화점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"전무점\">전무점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"주류/유흥업\">주류/유흥업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"병원/의료업\">병원/의료업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"기타\">기타</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <br /> <input type=\"text\" id=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align: left\">가격 정보</h3>\r\n");
      out.write("\t\t\t\t\t<span style=\"text-align: right; color: red;\"> 해당부분이 없으면 0을\r\n");
      out.write("\t\t\t\t\t\t입력하세요.</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-12 h-100\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 810px; height: 200px;\" class=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">매매가</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">전세가</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">보증금</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">월세</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">권리금</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><h3 class=\"text-uppercase m-0\">융자</h3></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='address' name=\"address\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 mb-3 mb-md-0\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"text-align: left\">담당자 정보</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"card py-4 h-100\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-top: 0.25rem solid #64a19d; border-bottom: none;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"text-align: left; margin: 0 auto; width: 800px; height: 100px;\" class=\"regist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">이름</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" id='managerName' name=\"managerName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th><h3 class=\"text-uppercase m-0\">휴대전화번호</h3></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><select name=\"phoneIdx\" id=\"phoneIdx\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"height: 30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> - <input type=\"tel\" id='managerPhone' name=\"managerPhone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100px\">- <input type=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid='managerPhone' name=\"managerPhone\" style=\"width: 100px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 class=\"text-uppercase m-0\">이메일</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"email\" id=\"email\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th><h3 class=\"text-uppercase m-0\">전화</h3></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><select name=\"\" id=\"\" class=\"stx\" style=\"height: 30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"031\">031</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"032\">032</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"033\">033</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"041\">041</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"042\">042</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"043\">043</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"051\">051</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"052\">052</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"053\">053</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"054\">054</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"055\">055</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"061\">061</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"062\">062</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"063\">063</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"064\">064</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"070\">070</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"050\">050</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> - <input type=\"tel\" id='managerPhone2' name=\"managerPhone2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100px\">- <input type=\"tel\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid='managerPhone2' name=\"managerPhone2\" style=\"width: 100px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<textarea\r\n");
      out.write("\t\t\t\t\tstyle=\"resize: none; width: 800px; height: 500px; margin-right: 800px;\"\r\n");
      out.write("\t\t\t\t\treadonly> 세미프로젝트는 정보통신부에서시행하는 정보통신망 이용촉진 등에 관한 법률상의 개인정보 보호제도에 따라 회원들의 개인정보 관리에 만전을 기하고 있으며 회원들이 마인애드의 모든 서비스를 안심하고 이용할수 있도록 하기 위해 항상 최선을 다하고 있습니다. 정부의 관련 법률 및 지침의 변경, 또는 마인애드의 정책 변화에 따라 개인정보보호정책은 임의로 변경될 수 있으니 사용자 보호 정책에 관심을 가지고 수시로 확인해주시기 바랍니다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t1.회원의 개인정보 수집목적 및 이용\r\n");
      out.write("당사는 이용자 확인, 이용대금 결제, 상품 배송 및 통계 분석을 통한 마케팅자료로써 귀하의 취향에 맞는 최적의 서비스를 제공하기 위한 목적으로 귀하의 개인정보를 수집 이용하고 있습니다. 당사 회원으로 등록하신 모든 고객의 개인정보는 위에서 밝힌 목적 이외에는 절대로 사용될 수 없으나, 회원 개인정보의 사용 목적과 용도가 변경될 경우에 반드시 당사 회원으로 등록하신 모든 고객님께 동의를 구할 것입니다.\r\n");
      out.write("\r\n");
      out.write("수집하는 개인정보 항목에 따른 구체적인 수집목적 및 이용목적은 다음과 같습니다.\r\n");
      out.write("\r\n");
      out.write("* 성명, 아이디, 비밀번호, 주민등록번호 : 회원제 서비스 이용에 따른 본인 확인 절차에 이용\r\n");
      out.write("* 이메일주소, 전화번호 : 고지사항 전달, 불만처리 등을 위한 원활한 의사소통 경로의 확보, 새로운 서비스 및 신상품이나 이벤트 정보 등의 안내\r\n");
      out.write("* 은행계좌정보, 신용카드정보 : 유료정보 이용 및 상품 구매에 대한 결제\r\n");
      out.write("* 주소, 전화번호 : 청구서, 경품 및 쇼핑물품 배송에 대한 정확한 배송지의 확보\r\n");
      out.write("* 기타 선택항목 : 개인맞춤 서비스를 제공하기 위한 자료\r\n");
      out.write("2.개인정보 수집 항목 및 보유, 이용기간\r\n");
      out.write("당사 회원을 대상으로 각종 서비스를 제공하기 위해 제공 받는 필수 회원정보는 다음과 같습니다.\r\n");
      out.write("\r\n");
      out.write("① 성명\r\n");
      out.write("② 주민등록번호(회원의 경우)\r\n");
      out.write("③ 주소\r\n");
      out.write("④ 전화번호(일반전화와 핸드폰)\r\n");
      out.write("⑤ 희망ID(회원의 경우)\r\n");
      out.write("⑥ 비밀번호(회원의 경우)\r\n");
      out.write("이외에 회원가입시 고객님이 원하실 경우에 추가 정보를 선택하여 제공하실 수 있도록 되어 있으며 일부 물품 및 서비스 상품에 대한 주문 및 접수시에 고객님이 원하시는 정확한 주문 내용을 파악하여 원활한 주문 및 결제와 배송을 위하여 추가 정보를 요구하고 있습니다.\r\n");
      out.write("\r\n");
      out.write("회원이 탈퇴하시거나 코센의 이용약관에 의한 회원 자격 상실의 경우에 당사가 보유한 해당 고객의 개인 정보는 지체 없이 파기됩니다.\r\n");
      out.write("\r\n");
      out.write("다만, 당사는 불량 회원의 부정한 이용의 재발을 방지하기 위해, 이용계약 해지일로부터 1년간 해당 회원의 주민등록번호를 보유할 수 있습니다. 그리고 상법, 전자상거래 등에서의 소비자보호에 관한 법률 등 관계법령의 규정에 의하여 보존할 필요가 있는 경우 회사는 관계법령에서 정한 일정한 기간 동안 회원정보를 보관합니다. 이 경우 회사는 회사는 보관하는 정보를 그 보관의 목적으로만 이용하며 보존기간은 아래와 같습니다.\r\n");
      out.write("\r\n");
      out.write("- 계약 또는 청약철회 등에 관한 기록 : 5년\r\n");
      out.write("- 대금결제 및 재화등의 공급에 관한 기록 : 5년\r\n");
      out.write("- 소비자의 불만 또는 분쟁처리에 관한 기록 : 3년\r\n");
      out.write("3.아동의 개인정보보호\r\n");
      out.write("당사는 \"정보통신망이용 촉진 및 정보보호등에 관한 법률 제31조 제1항\"에 의하여 만14세 미만의 아동의 개인정보 수집시 법정대리인의 동의를 받아야 합니다. 따라서, 당사는 만14세미만의 아동에 대해서는 개인정보를 받지 않을 뿐만 아니라, 회원으로 가입이 되지 않습니다. 단, 14세 미만의 아동은 법정대리인의 동의 및 서면 인증후에, 회원으로 가입할 수 있습니다. 또한, 만 14세 미만 아동의 법정 대리인은 아동의 개인정보의 열람, 정정, 동의 철회를 요청할 수 있으며 이런 요청이 있을 경우 당사는 지체 없이 필요한 조치를 취합니다.\r\n");
      out.write("\r\n");
      out.write("4.개인정보 제공 및 공유\r\n");
      out.write("당사 회원의 고객 개인정보는 원칙적으로 제3기관 및 제3자에게 제공 될 수 없으며 당사가 회원님께 편의를 제공하기 위하여 특정 회사에 개인정보를 제공하고자 할 경우에는 반드시 회원님께 해당되는 합당한 절차를 통하여 동의를 구하도록 되어 있습니다. 단, 다음 경우에 한하여 고객의 동의 없이 개인정보를 제공할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("① 업무상 배송업체에 배송에 필요한 최소한의 이용자정보(성명, 주소, 전화번호)를 알려주는 경우\r\n");
      out.write("② 통계작성, 학술연구 또는 시장조사를 위하여 필요한 경우로서 특정 개인을 식별할 수 없는 형태로 제공하는 경우\r\n");
      out.write("③ 정부 기관의 공식적 요청이 있을 경우.\r\n");
      out.write("5.개인정보 열람,정정 및 삭제처리\r\n");
      out.write("회원님이 원하실 경우 언제라도 당사에서 개인정보를 열람하실 수 있으며 보관된 필수 정보를 수정하실 수 있습니다. 또한 회원가입시 요구된 필수 정보 외의 추가 정보는 언제나 열람, 수정, 삭제할 수 있습니다. 회원님의 개인정보 변경 및 삭제와 회원탈퇴는 당사의 고객센터에서 로그인(Login) 후 이용하실 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("6.비회원고객의 개인정보관리\r\n");
      out.write("① 당사는 비회원 고객 또한 물품 및 서비스 상품의 구매를 하실 수 있습니다. 당사는 비회원 주문의 경우 배송 및 대금 결제, 상품 배송에 반드시 필요한 개인정보만을 고객님께 요청하고 있습니다.\r\n");
      out.write("② 당사에서 비회원으로 구입을 하신 경우 비회원 고객께서 입력하신 지불인 정보 및 수령인 정보는 대금 결제 및 상품 배송에 관련한 용도 외에는 다른 어떠한 용도로도 사용되지 않습니다.\r\n");
      out.write("7.내부 보안 대책\r\n");
      out.write("당사는 고객의 개인정보를 취급할 수 있는 인력을 최소한으로 한정하고 해당 인원에게 정기적, 부정기적 보안교육을 실시하고 있습니다. 또한 고객님의 개인정보를 열람할 수 있는 시스템에는 2차 암호 체제를 갖추고 외부 네트워크로부터 철저하게 격리시켜 외부 침입 및 내부 침입에 대응하고 있습니다.\r\n");
      out.write("\r\n");
      out.write("8.쿠키사용\r\n");
      out.write("당사는 쿠키를 사용하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("이상의 당사의 개인정보 보호정책은 사이트 오픈과 동시에 시행합니다.\r\n");
      out.write("당사는 개인정보 보호 관리책임자를 아래와 같이 지정합니다.\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t<br> <span style=\"position:relative;right:300px\"><input type=\"checkbox\" id=\"agree\" style=\"left:0\"> 개인정보 수집 및 이용동의에\r\n");
      out.write("\t\t\t\t관한 사항을 읽었으며, 이에 동의합니다. </span>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"btn\" id=\"submission\" value=\"매물등록\" style=\"position:relative;right:150px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/sidebar.css?after\" rel=\"stylesheet\" />\r\n");
      out.write("<div id=\"rightSide\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"right_zzim\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"recTit\">\r\n");
      out.write("\t\t\t비슷한 매물 정보 <span id=recentCnt></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul></ul>\r\n");
      out.write("\t\t<!-- 본 상품이 뿌려질 부분  -->\r\n");
      out.write("\t\t<div id=\"paging\">\r\n");
      out.write("\t\t\t<a class=\"btn_prev\" style=\"cursor: pointer\">이전</a><span\r\n");
      out.write("\t\t\t\tid=\"currentPage\"></span><span id=\"totalPageCount\"></span><a\r\n");
      out.write("\t\t\t\tclass=\"btn_next\" style=\"cursor: pointer\">다음</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- Footer-->\r\n");
      out.write("<footer class=\"footer bg-black small text-center text-white-50\">\r\n");
      out.write("\t<div class=\"container\">Copyright ⓒ Your Website 2020</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Bootstrap core JS-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar url = 'hyundoo.Project?page=commercial&subcode=1'\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t$('#combobox1').html(d);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t/* \t$('#combobox1')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t//마커 추가하기.\r\n");
      out.write("\t\t\t\t\t\t\tvar param = $(this).val();\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=6&guname='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param);\r\n");
      out.write("\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(typeof (d));\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar myObj = JSON.parse(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar i = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//console.log(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor ( var e in myObj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//console.log(\"e : \"+e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar marker = new naver.maps.Marker(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tposition : new naver.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmyObj[e].lat,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmyObj[e].lng),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmap : map\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}) */\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#combobox1')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar param = $('#combobox1').val()\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=2&guName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#combobox2').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=96&guName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#information').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tvar seoul = new naver.maps.LatLngBounds(new naver.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t37.42829747263545, 126.76620435615891),\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnew naver.maps.LatLng(37.7010174173061, 127.18379493229875));\r\n");
      out.write("\t\t\t\t\t\t\tvar map = new naver.maps.Map(document.getElementById('map'), {\r\n");
      out.write("\t\t\t\t\t\t\t\tminZoom : 10.5,\r\n");
      out.write("\t\t\t\t\t\t\t\tzoom : 10.5,\r\n");
      out.write("\t\t\t\t\t\t\t\tmapTypeId : 'normal',\r\n");
      out.write("\t\t\t\t\t\t\t\tcenter : new naver.maps.LatLng(37.4098871, 126.989261),\r\n");
      out.write("\t\t\t\t\t\t\t\tmaxBounds : seoul,\r\n");
      out.write("\t\t\t\t\t\t\t\tbaseTileOpacity : 0,\r\n");
      out.write("\t\t\t\t\t\t\t\tscaleControl: false,\r\n");
      out.write("\t\t\t\t\t            logoControl: false,\r\n");
      out.write("\t\t\t\t\t            mapDataControl: false,\r\n");
      out.write("\t\t\t\t\t            zoomControl: false,\r\n");
      out.write("\t\t\t\t\t            mapTypeControl: false\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t/* var HOME_PATH = window.HOME_PATH || '.'; */\r\n");
      out.write("\t\t\t\t\t\t\tnaver.maps.Event.once(map, 'init_stylemap', function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : 'json/'+$(this).val()+'.json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : startDataLayer\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar url = 'hyundoo.Project?page=commercial&subcode=3'\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t$('#combobox3').html(d);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#combobox3')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar param = $('#combobox3').val()\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=4&largeName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(param)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#combobox4').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#combobox4')\r\n");
      out.write("\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar largeName = $('#combobox3').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar mediumName = $('#combobox4').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar url = 'hyundoo.Project?page=commercial&subcode=5&largeName='\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(largeName)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \"&mediumName=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ encodeURIComponent(mediumName)\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#combobox5').html(d);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"Error : \" + e);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction goPopup() {\r\n");
      out.write("\t\t// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("\t\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\tvar pop = window.open(\"semi.Project?page=commercial&subcode=96\", \"pop\",\r\n");
      out.write("\t\t\t\t\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\r\n");
      out.write("\t\t// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\t//var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction jusoCallBack(roadFullAddr, roadAddrPart1, addrDetail,\r\n");
      out.write("\t\t\troadAddrPart2, engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn,\r\n");
      out.write("\t\t\tdetBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm, rn, udrtYn,\r\n");
      out.write("\t\t\tbuldMnnm, buldSlno, mtYn, lnbrMnnm, lnbrSlno, emdNo) {\r\n");
      out.write("\t\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("\t\t//document.form.roadFullAddr.value = roadFullAddr;\r\n");
      out.write("\t\t$('#roadAddrPart1').val(roadAddrPart1);\r\n");
      out.write("\t\t$(\"#addrDetail\").val(addrDetail);\r\n");
      out.write("\t\t$(\"#zipNo\").val(zipNo);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("<!-- \"검색\" 단추를 누르면 팝업 레이어가 열리도록 설정한다 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#postcodify_search_button\").postcodifyPopUp();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- Third party plugin JS-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("<!-- Core theme JS-->\r\n");
      out.write("<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
