/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-06-01 09:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/community/../include/footer.jsp", Long.valueOf(1590935123427L));
    _jspx_dependants.put("/WEB-INF/views/community/../include/header_menu.jsp", Long.valueOf(1591002295064L));
    _jspx_dependants.put("/WEB-INF/views/community/../include/header_index.jsp", Long.valueOf(1590932179513L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1588293609789L));
    _jspx_dependants.put("jar:file:/C:/ikosmo64/webapp/projectworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/uiProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"EUC-KR\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Grayscale - Start Bootstrap Theme</title>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Varela+Round\" rel=\"stylesheet\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"resources/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("  ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("       \r\n");
      out.write("          <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\" id=\"mainNav2\" >\r\n");
      out.write("         <div class=\"container .col-md-12\">\r\n");
      out.write("                <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">메인메뉴테스트</a><button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">Menu<i class=\"fas fa-bars\"></i></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                 <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                        <li class=\"nav-item2\"><a class=\"nav-link2 js-scroll-trigger\" href=\"#about\">강온유님 환영합니다.</a></li>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"semi.Project?page=estate&code=2\">매물 등록</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" onclick=\"location = 'semi.Project?page=community&code=1'\">커뮤니티</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"semi.Project?page=customer&code=1\">고객센터</a></li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"semi.Project?page=commercial&subcode=98\">상가</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                    </ul>\r\n");
      out.write("                      <ul class=\"navbar-nav ml-auto2\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#about\">내정보</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link js-scroll-trigger\" href=\"#projects\">로그아웃</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            </nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"projects-section bg-light\" id=\"projects\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"tab\" href=\"#all\">전체</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"tab\"\r\n");
      out.write("\t\t\t\thref=\"#qna\">질문</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"tab\"\r\n");
      out.write("\t\t\t\thref=\"#story\">이야기</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("\t\t\t<div class=\"tab-pane fade show active\" id=\"all\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p>'구'는 반드시 선택하여야 하며, 그 하위 지역을 포함하여 검색됩니다.</p>\r\n");
      out.write("\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"Select1\">지역</label> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control col-md-1\" id=\"Select1\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<option selected=\"selected\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강남구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강동구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강북구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강서구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>관악구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>광진구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>구로구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>금천구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>노원구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>도봉구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>동대문구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>동작구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>마포구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>서대문구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>서초구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>성동구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>성북구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>송파구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>양천구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>영등포구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>용산구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>은평구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>종로구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>중구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>중랑구</option>\r\n");
      out.write("\t\t\t\t\t</select> <label for=\"Select2\"\r\n");
      out.write("\t\t\t\t\t\t>매물종류</label> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control col-md-1\" id=\"Select2\">\r\n");
      out.write("\t\t\t\t\t\t<option selected=\"selected\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option>아파트</option>\r\n");
      out.write("\t\t\t\t\t\t<option>오피스텔</option>\r\n");
      out.write("\t\t\t\t\t\t<option>분양권</option>\r\n");
      out.write("\t\t\t\t\t\t<option>주택</option>\r\n");
      out.write("\t\t\t\t\t\t<option>토지</option>\r\n");
      out.write("\t\t\t\t\t\t<option>원룸</option>\r\n");
      out.write("\t\t\t\t\t\t<option>상가</option>\r\n");
      out.write("\t\t\t\t\t\t<option>사무실</option>\r\n");
      out.write("\t\t\t\t\t\t<option>공장</option>\r\n");
      out.write("\t\t\t\t\t\t<option>재개발</option>\r\n");
      out.write("\t\t\t\t\t\t<option>건물</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t>검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"checkorder1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"alloptions\" id=\"alloptions1\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option1\" checked=\"checked\" >최신순\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"alloptions\" id=\"alloptions2\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option2\">조회순\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"alloptions\" id=\"alloptions3\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option3\">추천순\r\n");
      out.write("\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-primary btn-sm\" id=\"writeBtn1\">글쓰기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">지역</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">조회</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">추천</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">강남구</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td >안녕하세요!</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>2020-05-27</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>27</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div id=\"pagenum1\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination pagination-lg\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">&laquo;</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">6</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">7</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">8</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">9</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">10</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-pane fade\" id=\"qna\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p>'구'는 반드시 선택하여야 하며, 그 하위 지역을 포함하여 검색됩니다.</p>\r\n");
      out.write("\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"Select1\">지역</label> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control col-md-1\" id=\"Select1\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<option selected=\"selected\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강남구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강동구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강북구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강서구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>관악구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>광진구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>구로구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>금천구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>노원구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>도봉구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>동대문구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>동작구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>마포구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>서대문구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>서초구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>성동구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>성북구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>송파구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>양천구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>영등포구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>용산구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>은평구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>종로구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>중구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>중랑구</option>\r\n");
      out.write("\t\t\t\t\t</select> <label for=\"Select2\"\r\n");
      out.write("\t\t\t\t\t\t>매물종류</label> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control col-md-1\" id=\"Select2\">\r\n");
      out.write("\t\t\t\t\t\t<option selected=\"selected\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option>아파트</option>\r\n");
      out.write("\t\t\t\t\t\t<option>오피스텔</option>\r\n");
      out.write("\t\t\t\t\t\t<option>분양권</option>\r\n");
      out.write("\t\t\t\t\t\t<option>주택</option>\r\n");
      out.write("\t\t\t\t\t\t<option>토지</option>\r\n");
      out.write("\t\t\t\t\t\t<option>원룸</option>\r\n");
      out.write("\t\t\t\t\t\t<option>상가</option>\r\n");
      out.write("\t\t\t\t\t\t<option>사무실</option>\r\n");
      out.write("\t\t\t\t\t\t<option>공장</option>\r\n");
      out.write("\t\t\t\t\t\t<option>재개발</option>\r\n");
      out.write("\t\t\t\t\t\t<option>건물</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t>검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"checkorder2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"queoption\" id=\"queoption1\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option4\" checked=\"checked\">최신순\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"queoption\" id=\"queoption2\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option5\">조회순\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"queoption\" id=\"queoption3\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option6\">추천순\r\n");
      out.write("\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-primary btn-sm\" id=\"writeBtn2\">글쓰기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">지역</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">조회</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">추천</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">강남구</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td >안녕하세요!</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>2020-05-27</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>27</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div id=\"pagenum2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination pagination-lg\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">&laquo;</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">6</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">7</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">8</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">9</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">10</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab-pane fade\" id=\"story\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p>'구'는 반드시 선택하여야 하며, 그 하위 지역을 포함하여 검색됩니다.</p>\r\n");
      out.write("\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"Select1\">지역</label> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control col-md-1\" id=\"Select1\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<option selected=\"selected\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강남구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강동구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강북구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>강서구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>관악구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>광진구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>구로구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>금천구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>노원구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>도봉구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>동대문구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>동작구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>마포구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>서대문구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>서초구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>성동구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>성북구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>송파구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>양천구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>영등포구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>용산구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>은평구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>종로구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>중구</option>\r\n");
      out.write("\t\t\t\t\t\t<option>중랑구</option>\r\n");
      out.write("\t\t\t\t\t</select> <label for=\"Select2\">매물종류</label> <select\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control col-md-1\" id=\"Select2\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<option selected=\"selected\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option>아파트</option>\r\n");
      out.write("\t\t\t\t\t\t<option>오피스텔</option>\r\n");
      out.write("\t\t\t\t\t\t<option>분양권</option>\r\n");
      out.write("\t\t\t\t\t\t<option>주택</option>\r\n");
      out.write("\t\t\t\t\t\t<option>토지</option>\r\n");
      out.write("\t\t\t\t\t\t<option>원룸</option>\r\n");
      out.write("\t\t\t\t\t\t<option>상가</option>\r\n");
      out.write("\t\t\t\t\t\t<option>사무실</option>\r\n");
      out.write("\t\t\t\t\t\t<option>공장</option>\r\n");
      out.write("\t\t\t\t\t\t<option>재개발</option>\r\n");
      out.write("\t\t\t\t\t\t<option>건물</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-primary btn-sm\"\r\n");
      out.write("\t\t\t\t\t\t>검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"checkorder3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"storyoption\" id=\"storyoption1\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option7\" checked=\"checked\">최신순\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"storyoption\" id=\"storyoption2\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option8\">조회순\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-check-label\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-input\" name=\"storyoption\" id=\"storyoption3\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"option9\">추천순\r\n");
      out.write("\t\t\t\t\t\t</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-primary btn-sm\" id=\"writeBtn3\">글쓰기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">지역</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">조회</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">추천</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">강남구</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td >안녕하세요!</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>2020-05-27</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>27</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div id=\"pagenum3\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination pagination-lg\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">&laquo;</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">6</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">7</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">8</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">9</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">10</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#writeBtn1').click(function() {\r\n");
      out.write("\t\t\tlocation = 'semi.Project?page=community&code=7';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#writeBtn2').click(function() {\r\n");
      out.write("\t\t\tlocation = 'semi.Project?page=community&code=7';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#writeBtn3').click(function() {\r\n");
      out.write("\t\t\tlocation = 'semi.Project?page=community&code=8';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer bg-black small text-center text-white-50\"><div class=\"container\">Copyright ⓒ   Your Website 2020</div></footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("      \r\n");
      out.write("        <script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Third party plugin JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"resources/js/scripts.js\"></script>\r\n");
      out.write("        <script src=\"resources/js/text.js\"></script>\r\n");
      out.write("         <script>\r\n");
      out.write("         $(function() {\r\n");
      out.write("        \t \r\n");
      out.write("        \t    $(\".typer\").typed({\r\n");
      out.write("         \t\t    strings: [\" C조 Project\", \" Test용 문구\", \" 조장 : 박현두\", \" 대박임\"],\r\n");
      out.write("         \t\t    typeSpeed: 500,\r\n");
      out.write("         \t\t    backDelay: 1500,\r\n");
      out.write("         \t\t    showCursor: false\r\n");
      out.write("         \t\t});\r\n");
      out.write("        \t    $('#filter_close').click(function() {\n");
      out.write("        \t    \t$('.filter-page').slideUp(1000).addClass('invisible').removeClass('visible');\r\n");
      out.write("        \t    \tclassName='invisible';\r\n");
      out.write("        \t    \tinvisible='invisible';\r\n");
      out.write("        \t    \tvisible='visible';\r\n");
      out.write("        \t    \t        \n");
      out.write("        \t    })\r\n");
      out.write("        \t    \r\n");
      out.write("        \t    $('.card').click(function() {\n");
      out.write("        \t    \t\tvar num=$(this).index();\r\n");
      out.write("        \t    \t\tconsole.log(num)\n");
      out.write("        \t    });\r\n");
      out.write("        \t    var invisible='invisible';\r\n");
      out.write("        \t    var visible='visible';\r\n");
      out.write("        \t    var className='invisible';\r\n");
      out.write("        \t   $('.filter-div').children('.btn').click(function() {\r\n");
      out.write("        \t\t  \r\n");
      out.write("           \t\t \r\n");
      out.write("        \t\t   \t$('.filter-page').removeClass(invisible);\r\n");
      out.write("       \t   \t\t\t$('.filter-page').addClass(visible);\r\n");
      out.write("        \t\t \tif(className === 'visible'){\r\n");
      out.write("        \t\t \t      \r\n");
      out.write("        \t\t \t\t$('.filter-page').slideUp(1000);\r\n");
      out.write("        \t\t \t\t\r\n");
      out.write("        \t\t \t}else {\r\n");
      out.write("        \t\t \t\t\r\n");
      out.write("        \t\t \t\t$('.filter-page').slideDown(1000);\r\n");
      out.write("        \t\t \t\t\r\n");
      out.write("        \t\t \t}\n");
      out.write("        \t\t \t\t\r\n");
      out.write("            \t   \t\tclassName=visible;\r\n");
      out.write("            \t   \t\tvisible=invisible;\r\n");
      out.write("            \t   \t\tinvisible=className;\n");
      out.write("        \t\t \t\r\n");
      out.write("        \t\t \t\n");
      out.write("        \t\t \t\n");
      out.write("        \t   });\r\n");
      out.write("        \t    \r\n");
      out.write("        \t    \r\n");
      out.write("\t\t});\r\n");
      out.write("         \r\n");
      out.write("     \r\n");
      out.write("                    </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
